#feign:
#    client:
#        config:
#            #定义FeignClient的名称
#            RedisOneClient:
#                # 建立链接的超时时长
#                connectTimeout: 5000
#                # 读取超时时长
#                readTimeout: 5000
#                # 配置Feign的日志级别
#                loggerLevel: full
#                # Feign的错误解码器
#                errorDecoder: com.example.SimpleErrorDecoder
#                # 配置重试
#                retryer: com.example.SimpleRetryer
#                # 配置请求拦截器
#                requestInterceptors:
#                #配置熔断不处理404异常
#                decode404: false
#
#                #配置feign日志的输出
#                #日志级别  NONE : 不输出日志(高)   BASIC: 适用于生产环境追踪问题    HEADERS : 在BASIC的基础上,记录请求和响应头信息   FULL : 记录所有
#                redis-demo:  #需要调用的服务名称
#                    loggerLevel: FULL   #日志级别
#
#    #Spring Cloud Feign 支持对请求和响应进行GZIP压缩，以减少通信过程中的性能损耗。通过下面的参数即可开启请求与响应的压缩功能：
#    compression:
#        request:
#            enabled: true # 开启请求压缩
#            mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
#            min-request-size: 2048 # 设置触发压缩的大小下限
#        response:
#            enabled: true # 开启响应压缩